name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install node
      uses: actions/setup-node@v4

    - name: install wasm-pack
      run: npm install -g wasm-pack

    - name: Build sljs
      run: cargo build --verbose

    - name: Build sljs_wasm
      run: cd wasm && wasm-pack build

    - name: Test sljs
      run: cargo test --verbose

    - name: Test sljs_wasm
      run: cd wasm && wasm-pack test --node
